workspace:
  base: /go
  path: src/github.com/Jyrno42/drone-docker

pipeline:
  test:
    image: golang:1.6
    environment:
      - CGO_ENABLED=0
    commands:
      # Disabled: main.go:99: cli.StringSlice composite literal uses unkeyed fields
      # - go vet
      - go test -cover -coverprofile=coverage.out
      - go build -ldflags "-s -w -X main.build=$DRONE_BUILD_NUMBER" -a -tags netgo

  publish:
    image: thorgate/drone-docker-compose
    repo: thorgate/drone-docker-compose
    tags: [ "latest", "0.0.1" ]
    when:
      branch: master
      event: push
